dist: bionic

cache:
  directories:
    - iso

language: python
python:
  - "3.6"
virtualenv:
  system_site_packages: true

before_install:
  - sudo ./install-virtualbox-builder.sh
  - sudo ./install-packer.sh

install:
  - pip3 install -r requirements.txt

script:
  - sudo python3 builder.py $VAGRANT_ACCESS_TOKEN
