language: python

cache:
  directories:
    - iso

python:
  - "3.6"

before_install:
  - sudo ./install-virtualbox-builder.sh
  - sudo ./install-packer.sh

install:
  - pip install -r requirements.txt

script:
  - sudo python3 builder.py $VAGRANT_ACCESS_TOKEN
