dist: bionic
sudo: required

cache:
  directories:
    - iso

language: python
python:
  - "3.6"
virtualenv:
  system_site_packages: true

before_install:
  - ./install-virtualbox-builder.sh
  - ./install-packer.sh

install:
  - pip install -r requirements.txt

script:
  - python builder.py $VAGRANT_ACCESS_TOKEN
