dist: bionic

cache:
  directories:
    - packer_cache 

language: python
python:
  - "3.6"
virtualenv:
  system_site_packages: true

before_install:
  - sudo ./install-virtualbox-builder.sh
  - sudo ./install-packer.sh

install:
  - pip3 install -r requirements.txt

script:
  - /usr/local/packer --version
  - travis_wait 30 python3 builder.py $VAGRANT_ACCESS_TOKEN
