---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - geerlingguy.nfs
  #  - geerlingguy.packer-debian
    - catosplace.packer_debian

  tasks:
    - name: Install some helpful utilities
      apt:
        name: 
          - git
          - wget
          - curl
          - vim
        state: present
